-- =====================================================================
-- B5.5 — QUÉ SABE HACER CADA PROFESIONAL
-- Funcionalidad PREMIUM: «servicios_por_profesional»
-- Fecha: 2026-08-06
--
-- «Es que Borja no hace color.» Hasta hoy el sistema no lo sabía y podía
-- asignarle un tinte. La peluquería lo descubría con la clienta sentada.
--
-- UNA SOLA REGLA, y es la misma que la de los turnos (por algo: en cuanto
-- hay dos reglas parecidas con comportamientos distintos, alguien se
-- equivoca):
--
--     Sin ninguna fila = hace TODOS los servicios.
--     Con alguna fila  = hace SOLO los marcados.
--
-- Por eso instalar esto no cambia nada por sí solo: la tabla nace vacía,
-- todo el mundo lo hace todo, y la peluquería solo toca a quien tenga una
-- excepción real. Es lo contrario de obligar a marcar 8 servicios × 5
-- personas antes de que el asistente vuelva a funcionar.
--
-- Tabla aparte de `service_resources` a propósito: aquélla dice «este
-- servicio NECESITA este aparato» y ésta dice «esta persona SABE hacer este
-- servicio». Mismo par de columnas, significado opuesto. Mezclarlas sería
-- ahorrarse una tabla para pagarlo en un bug.
--
-- Idempotente: se puede ejecutar varias veces sin efecto secundario.
-- =====================================================================

create table if not exists public.resource_skills (
  id          bigint generated by default as identity primary key,
  store_id    uuid   not null references public.stores (id)    on delete cascade,
  resource_id bigint not null references public.resources (id) on delete cascade,
  service_id  bigint not null references public.services (id)  on delete cascade,
  created_at  timestamptz not null default now()
);

comment on table public.resource_skills is
  'Qué servicios sabe hacer cada profesional. SIN filas para una persona = los hace todos.';

-- Una persona no puede saber hacer dos veces lo mismo
create unique index if not exists resource_skills_unico
  on public.resource_skills (resource_id, service_id);

-- Índice de lectura: el motor pide siempre «todas las de esta tienda»
create index if not exists resource_skills_store_idx
  on public.resource_skills (store_id, resource_id);

alter table public.resource_skills enable row level security;

-- Comprobación
select
  (select count(*) from public.resource_skills)                    as filas,
  (select count(distinct resource_id) from public.resource_skills) as personas_con_limite;
