-- =====================================================================
-- Migración: módulo "Llamada perdida → WhatsApp" (missed-call) — M1
-- =====================================================================
-- Idempotente (IF NOT EXISTS). Ejecutar en Supabase SQL Editor tras OK.
-- Aditiva: no modifica ninguna tabla existente.
--
-- Cadena multi-tenant del módulo:
--   webhook voz (Twilio) → did_e164 (campo To) → store_phone_numbers
--   → store_id → resto. El store_id JAMÁS llega del exterior.
--
-- Decisiones cerradas (2026-07-08):
--   * Dedupe: 1 plantilla por (tienda, teléfono) por DÍA NATURAL en la
--     timezone de la tienda, garantizado con PK compuesta + captura 23505.
--   * Botón "Que me llamen": solo se registra (callback_requested).
--   * resulted_in_booking_id es BIGINT (appointments.id es bigint, no uuid).
-- =====================================================================

-- ---------------------------------------------------------------------
-- 1) STORE_PHONE_NUMBERS — DIDs de voz por tienda (mapeo DID → store_id)
-- ---------------------------------------------------------------------
create table if not exists public.store_phone_numbers (
  id          uuid primary key default gen_random_uuid(),
  store_id    uuid not null references public.stores (id) on delete cascade,
  provider    text not null default 'twilio',
  did_e164    text not null,          -- formato E.164 con '+', p. ej. +34911234567
  is_active   boolean not null default true,
  created_at  timestamptz not null default now()
);

-- Un DID pertenece a una sola fila en todo el sistema (es la clave de routing)
create unique index if not exists store_phone_numbers_did_unique
  on public.store_phone_numbers (did_e164);

create index if not exists store_phone_numbers_store_id_idx
  on public.store_phone_numbers (store_id);

-- ---------------------------------------------------------------------
-- 2) MISSED_CALL_SETTINGS — configuración del módulo por tienda
-- ---------------------------------------------------------------------
create table if not exists public.missed_call_settings (
  store_id           uuid primary key references public.stores (id) on delete cascade,
  enabled            boolean not null default false,
  monthly_quota      integer not null default 100,
  business_name      text,             -- variable {{1}} de la plantilla
  template_name      text not null default 'canalagenda_missed_call_v1',
  template_language  text not null default 'es',
  -- Visible en dashboard/venta: tiendas "esperando a Meta" (aprobación 24-72 h)
  template_status    text not null default 'pending'
                       check (template_status in ('pending', 'approved', 'rejected')),
  -- Horario silencioso en hora LOCAL de la tienda (stores.timezone)
  quiet_start        time not null default '21:00',
  quiet_end          time not null default '09:00',
  -- Para atribución en euros: "N citas recuperadas ≈ N × ticket_medio €"
  ticket_medio_eur   numeric(8,2),
  created_at         timestamptz not null default now(),
  updated_at         timestamptz not null default now()
);

-- ---------------------------------------------------------------------
-- 3) MISSED_CALLS — registro de llamadas capturadas y su ciclo de vida
-- ---------------------------------------------------------------------
create table if not exists public.missed_calls (
  id                        bigint generated by default as identity primary key,
  store_id                  uuid not null references public.stores (id) on delete cascade,
  caller_phone              text,      -- formato Meta (dígitos sin '+'); null si anónima
  is_anonymous              boolean not null default false,
  did_e164                  text not null,
  provider                  text not null default 'twilio',
  provider_call_id          text,      -- CallSid de Twilio (idempotencia del webhook de voz)
  occurred_at               timestamptz not null default now(),
  -- Ciclo de vida del envío de plantilla:
  --   pending  → en cola (p. ej. horario silencioso; la cola ES esta tabla)
  --   sent     → plantilla enviada
  --   skipped  → no se enviará (ver skip_reason)
  status                    text not null default 'pending'
                              check (status in ('pending', 'sent', 'skipped')),
  skip_reason               text
                              check (skip_reason is null or skip_reason in
                                ('quota_exceeded', 'optout', 'anonymous', 'disabled',
                                 'template_not_approved', 'dedupe_24h', 'no_whatsapp_account')),
  template_sent_at          timestamptz,
  wa_message_id             text,
  -- Interacción posterior:
  callback_requested        boolean not null default false,  -- botón "Que me llamen"
  resulted_in_conversation  boolean not null default false,
  resulted_in_booking_id    bigint references public.appointments (id) on delete set null,
  created_at                timestamptz not null default now()
);

-- Idempotencia del webhook de voz: Twilio puede reintentar el mismo CallSid
create unique index if not exists missed_calls_provider_call_unique
  on public.missed_calls (provider, provider_call_id)
  where provider_call_id is not null;

-- Cola de despacho (horario silencioso): pendientes por tienda
create index if not exists missed_calls_pending_idx
  on public.missed_calls (store_id, occurred_at)
  where status = 'pending';

-- Métricas y listados por tienda/mes
create index if not exists missed_calls_store_occurred_idx
  on public.missed_calls (store_id, occurred_at desc);

-- ---------------------------------------------------------------------
-- 4) MISSED_CALL_SENDS — dedupe: 1 plantilla / (tienda, teléfono) / día natural
--    Se inserta ANTES de enviar; el 23505 garantiza exactly-once bajo carreras
--    (mismo patrón que la idempotencia de messages). sent_on se calcula en
--    backend con luxon en la timezone de la tienda.
-- ---------------------------------------------------------------------
create table if not exists public.missed_call_sends (
  store_id    uuid not null references public.stores (id) on delete cascade,
  phone       text not null,           -- formato Meta (dígitos sin '+')
  sent_on     date not null,           -- día natural LOCAL de la tienda
  created_at  timestamptz not null default now(),
  primary key (store_id, phone, sent_on)
);

-- ---------------------------------------------------------------------
-- 5) CONTACT_OPTOUTS — exclusión permanente por tienda
--    Se activa SOLO con payload del botón "No, gracias" o palabra BAJA.
--    (El "NO" textual conserva su significado actual: cancelar reserva pendiente.)
-- ---------------------------------------------------------------------
create table if not exists public.contact_optouts (
  store_id    uuid not null references public.stores (id) on delete cascade,
  phone       text not null,           -- formato Meta (dígitos sin '+')
  source      text not null default 'missed_call',
  created_at  timestamptz not null default now(),
  primary key (store_id, phone)
);

-- ---------------------------------------------------------------------
-- 6) RLS — igual que el resto: acceso solo vía backend con service_role
-- ---------------------------------------------------------------------
alter table public.store_phone_numbers  enable row level security;
alter table public.missed_call_settings enable row level security;
alter table public.missed_calls         enable row level security;
alter table public.missed_call_sends    enable row level security;
alter table public.contact_optouts      enable row level security;

-- =====================================================================
-- VERIFICACIÓN (tras ejecutar; debe devolver las 5 tablas):
--   select table_name from information_schema.tables
--   where table_schema='public' and table_name in
--     ('store_phone_numbers','missed_call_settings','missed_calls',
--      'missed_call_sends','contact_optouts')
--   order by 1;
-- =====================================================================
