-- =====================================================================
-- VIGILANCIA DEL PLANIFICADOR
-- Fecha: 2026-08-06
--
-- Por qué existe: el cron externo se ha caído DOS veces sin que nos
-- enterásemos. En julio estuvo semanas muerto (se autodesactivó tras varios
-- errores HTTP) y el 5 de agosto volvió a fallar con 401 tras rotar el token.
-- Nadie llama al backend, así que no hay error que ver: el sistema
-- simplemente deja de mandar recordatorios y de vigilar el calendario.
--
-- Con esta tabla, cada pasada del despachador deja constancia y /admin puede
-- decir «última ejecución: hace 4 minutos» — o gritar si hace media hora que
-- no sabe nada. Lo que no se vigila, se cae en silencio.
--
-- Idempotente: se puede ejecutar varias veces sin efecto secundario.
-- =====================================================================

create table if not exists public.cron_runs (
  id       bigint generated by default as identity primary key,
  ran_at   timestamptz not null default now(),
  origen   text,          -- 'cron-job.org', 'github-actions', 'manual'...
  resumen  jsonb          -- qué hizo esa pasada (recordatorios, sync, etc.)
);

create index if not exists cron_runs_ran_at_idx
  on public.cron_runs (ran_at desc);

-- Comprobación
select
  (select count(*) from public.cron_runs)                       as pasadas,
  (select max(ran_at) from public.cron_runs)                    as ultima;
