-- ============================================================
-- Migración bloque 1 (doc 12): cierres puntuales y vacaciones
-- Idempotente. El horario semanal ya existe (store_business_hours);
-- esto añade los cierres por RANGO de fechas (festivos, vacaciones).
-- El backend es tolerante: si esta tabla no existe, se comporta como
-- hasta ahora (solo horario semanal).
-- ============================================================

create table if not exists public.store_closures (
  id          bigint generated by default as identity primary key,
  store_id    uuid not null references public.stores (id) on delete cascade,
  start_date  date not null,
  end_date    date not null,
  reason      text,
  created_at  timestamptz not null default now(),
  constraint store_closures_rango_valido check (end_date >= start_date)
);

create index if not exists store_closures_store_range_idx
  on public.store_closures (store_id, start_date, end_date);

alter table public.store_closures enable row level security;

comment on table public.store_closures is
  'Cierres puntuales y vacaciones por rango de fechas (doc 12, bloque 1). Se suman al horario semanal de store_business_hours.';

-- Verificación:
--   select * from store_closures order by start_date;
