-- BLOQUEOS DE HORAS — «el jueves de 12 a 14 no cojas nada»
--
-- Hasta ahora solo se podían bloquear DÍAS ENTEROS:
--   · store_closures      → la tienda cierra (fechas, sin horas)
--   · resource_absences   → vacaciones de una persona (fechas, sin horas)
--
-- Faltaba lo que más se usa a diario: un rato. El comercial, la formación,
-- el médico, recoger a los niños. El único apaño era crear el evento en
-- Google Calendar, y con equipo NO funciona bien: un evento de calendario
-- ocupa a UNA persona, así que con tres en plantilla el hueco se seguía
-- ofreciendo.
--
-- `resource_id` NULL = afecta a TODA la tienda. Con valor = solo esa persona.
-- Es la casilla «¿a quién afecta?» del panel.

create table if not exists public.store_blocks (
  id          bigint generated by default as identity primary key,
  store_id    uuid not null references public.stores (id)    on delete cascade,
  -- NULL = toda la tienda. Si se borra a la persona, se va su bloqueo con ella.
  resource_id bigint          references public.resources (id) on delete cascade,
  start_at    timestamptz not null,
  end_at      timestamptz not null,
  reason      text,
  created_at  timestamptz not null default now(),
  constraint store_blocks_rango check (end_at > start_at)
);

comment on table public.store_blocks is
  'Bloqueos de horas concretas. resource_id NULL = toda la tienda.';

-- El motor pregunta siempre «qué bloqueos pisan este día en esta tienda»
create index if not exists store_blocks_store_rango_idx
  on public.store_blocks (store_id, start_at, end_at);

alter table public.store_blocks enable row level security;

-- El backend entra con service_role (se salta RLS). Estas políticas existen
-- para que NADIE pueda leerlos con la clave pública, igual que el resto de
-- tablas del proyecto.
drop policy if exists store_blocks_sin_acceso_publico on public.store_blocks;
create policy store_blocks_sin_acceso_publico
  on public.store_blocks for all
  using (false) with check (false);
