-- =====================================================================
-- ERRORES DEL SISTEMA VISIBLES
-- Fecha: 2026-08-10
--
-- Hoy, cuando algo revienta, se escribe en los logs de Render y ahí se
-- queda. Nadie los lee, y menos un sábado. Dos ReferenceError han vivido
-- semanas en producción por eso mismo.
--
-- Esta tabla es el buzón: cada error se apunta AGRUPADO por dónde ocurrió
-- y qué decía. Si el mismo fallo pasa doscientas veces no genera doscientas
-- filas, genera una con `veces = 200`. Un buzón que se inunda es otra forma
-- de no enterarse.
--
-- Se guarda lo mínimo para diagnosticar y NADA de contenido de clientes:
-- ni teléfonos, ni nombres, ni el texto de los mensajes. Si algún día hay
-- que enseñar esta tabla a alguien, que no haya nada que ocultar.
--
-- Idempotente: se puede ejecutar varias veces sin efecto secundario.
-- =====================================================================

create table if not exists public.system_errors (
  id          bigint generated by default as identity primary key,
  -- Con qué tienda tiene que ver (null = del sistema, no de una tienda)
  store_id    uuid references public.stores (id) on delete cascade,
  -- Dónde: 'webhook', 'api', 'cron', 'proceso'…
  ambito      text not null,
  -- Firma del error: se usa para agrupar. Mensaje recortado, sin datos.
  mensaje     text not null,
  -- Pista para diagnosticar: ruta, tipo de error, primeras líneas de pila
  detalle     jsonb,
  veces       integer not null default 1,
  primera_at  timestamptz not null default now(),
  ultima_at   timestamptz not null default now(),
  -- Cuando se marca como visto desde /admin deja de dar la lata
  visto_at    timestamptz
);

comment on table public.system_errors is
  'Errores del backend agrupados, para que se vean en /admin en vez de morir en los logs. Sin datos de clientes.';

-- La agrupación: mismo ámbito + mismo mensaje + misma tienda = una fila.
-- `coalesce` porque en Postgres NULL nunca es igual a NULL, y sin esto los
-- errores del sistema (sin tienda) se duplicarían uno por uno.
create unique index if not exists system_errors_firma
  on public.system_errors (ambito, mensaje, coalesce(store_id, '00000000-0000-0000-0000-000000000000'::uuid));

create index if not exists system_errors_ultima_idx
  on public.system_errors (ultima_at desc);

alter table public.system_errors enable row level security;

-- Apunta un error y agrupa. Devuelve cuántas veces va.
-- Al reaparecer un error ya marcado como visto, `visto_at` se borra: si ha
-- vuelto, es que no estaba resuelto.
create or replace function public.registrar_error_sistema(
  p_store_id uuid,
  p_ambito   text,
  p_mensaje  text,
  p_detalle  jsonb
)
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  total integer;
begin
  insert into public.system_errors (store_id, ambito, mensaje, detalle)
  values (p_store_id, p_ambito, left(p_mensaje, 300), p_detalle)
  on conflict (ambito, mensaje, coalesce(store_id, '00000000-0000-0000-0000-000000000000'::uuid))
  do update set
    veces     = public.system_errors.veces + 1,
    ultima_at = now(),
    detalle   = excluded.detalle,
    visto_at  = null
  returning veces into total;
  return total;
end;
$$;

-- Comprobación
select
  (select count(*) from public.system_errors)                      as errores,
  (select count(*) from information_schema.routines
     where routine_name = 'registrar_error_sistema')               as funcion;
