-- Migración B2 (doc 08 §2): catálogo de servicios por vertical.
-- Idempotente. Ejecutar en Supabase SQL Editor.
--
-- El motor es único; el vertical es configuración: vertical_code + services
-- (+ resources, preparado para B5). La cita guarda service_id/resource_id/extra.

-- 1) Vertical de la tienda ('peluqueria' | 'taller' | null = genérico)
alter table public.stores add column if not exists vertical_code text;

-- 2) Catálogo de servicios por tienda
create table if not exists public.services (
  id                bigint generated by default as identity primary key,
  store_id          uuid not null references public.stores(id) on delete cascade,
  name              text not null,
  duration_minutes  integer not null check (duration_minutes > 0),
  price_eur         numeric(8,2),            -- null = no mostrar precio
  description       text,                    -- fila de la lista (≤ 72 chars)
  mode              text not null default 'slot' check (mode in ('slot','franja')),
  is_active         boolean not null default true,
  sort_order        integer not null default 0,
  created_at        timestamptz not null default now()
);
create index if not exists services_store_active_idx
  on public.services (store_id, is_active, sort_order);

-- 3) Recursos (empleado/elevador/sala). B2: solo estructura; se usa en B5.
create table if not exists public.resources (
  id          bigint generated by default as identity primary key,
  store_id    uuid not null references public.stores(id) on delete cascade,
  name        text not null,
  kind        text not null default 'empleado'
                check (kind in ('empleado','elevador','sala','otro')),
  is_active   boolean not null default true,
  sort_order  integer not null default 0,
  created_at  timestamptz not null default now()
);
create index if not exists resources_store_active_idx
  on public.resources (store_id, is_active, sort_order);

-- 4) La cita conoce su servicio, recurso y datos del vertical
alter table public.appointments add column if not exists service_id  bigint references public.services(id)  on delete set null;
alter table public.appointments add column if not exists resource_id bigint references public.resources(id) on delete set null;
alter table public.appointments add column if not exists extra       jsonb;

alter table public.services  enable row level security;
alter table public.resources enable row level security;

-- ⚠️ NOTA (doc 08 §2): el índice anti doble-reserva actual implica UNA cita
-- simultánea por tienda. Se mantiene a propósito en B2. El multi-recurso real
-- (capacidad > 1) llegará en B5 con su migración consciente y probada.

-- VERIFICACIÓN:
-- select table_name from information_schema.tables
-- where table_schema='public' and table_name in ('services','resources');
