-- ============================================================
-- Migración P3: lista de espera (doc 09 §P3) — idempotente
-- El módulo solo actúa si la tienda tiene el flag premium "waitlist".
-- El hueco liberado NUNCA se bloquea: el primero que confirma se lo
-- queda (el índice anti doble-reserva resuelve la carrera).
-- ============================================================

create table if not exists public.waitlist (
  id            bigint generated by default as identity primary key,
  store_id      uuid not null references public.stores (id) on delete cascade,
  customer_id   bigint not null references public.customers (id) on delete cascade,
  service_id    bigint references public.services (id) on delete set null,
  desired_date  date,                      -- día deseado (null = cualquier día)
  status        text not null default 'waiting'
                  check (status in ('waiting','notified','converted','cancelled','expired')),
  created_at    timestamptz not null default now(),
  notified_at   timestamptz
);

create index if not exists waitlist_store_status_idx
  on public.waitlist (store_id, status, desired_date);

-- Dedupe: máx. 1 entrada EN ESPERA por tienda+cliente+día (23505 en el código)
create unique index if not exists waitlist_unique_waiting
  on public.waitlist (store_id, customer_id, coalesce(desired_date, '1900-01-01'::date))
  where status = 'waiting';

alter table public.waitlist enable row level security;

-- Verificación:
--   select * from waitlist limit 5;
