-- ============================================================
-- B5.1 — EQUIPO: personas con turno y ausencias  (doc 12 bloque 2)
-- Idempotente. Contiene la MIGRACIÓN CONSCIENTE del índice
-- anti doble-reserva: léela entera antes de ejecutarla.
-- ============================================================

-- 1) Turnos de cada persona (qué días y en qué horas trabaja).
--    Sin filas para una persona = trabaja todo el horario de la tienda.
create table if not exists public.resource_schedules (
  id          bigint generated by default as identity primary key,
  store_id    uuid not null references public.stores (id) on delete cascade,
  resource_id bigint not null references public.resources (id) on delete cascade,
  weekday     smallint not null check (weekday >= 0 and weekday <= 6),  -- 0 = domingo
  open_time   time not null,
  close_time  time not null,
  created_at  timestamptz not null default now(),
  constraint resource_schedules_horas check (close_time > open_time)
);
create index if not exists resource_schedules_recurso_idx
  on public.resource_schedules (resource_id, weekday);
create index if not exists resource_schedules_store_idx
  on public.resource_schedules (store_id, weekday);

-- 2) Ausencias por rango (vacaciones, baja, día libre puntual)
create table if not exists public.resource_absences (
  id          bigint generated by default as identity primary key,
  store_id    uuid not null references public.stores (id) on delete cascade,
  resource_id bigint not null references public.resources (id) on delete cascade,
  start_date  date not null,
  end_date    date not null,
  reason      text,
  created_at  timestamptz not null default now(),
  constraint resource_absences_rango check (end_date >= start_date)
);
create index if not exists resource_absences_recurso_idx
  on public.resource_absences (resource_id, start_date, end_date);

alter table public.resource_schedules enable row level security;
alter table public.resource_absences  enable row level security;

-- 3) Unidades por recurso (para la ENTREGA 2: aparatos con varias unidades).
--    Las personas siempre valen 1.
alter table public.resources add column if not exists units integer not null default 1;

-- ============================================================
-- 4) ⚠️ MIGRACIÓN CONSCIENTE DEL CANDADO ANTI DOBLE-RESERVA
--
--    ANTES: (store_id, start_at) donde status='confirmed'
--           → una sola cita por tienda y hora. Impide tener 2 peluqueras.
--
--    AHORA: (store_id, coalesce(resource_id, 0), start_at) donde confirmed
--           → una cita por PERSONA y hora.
--
--    El coalesce es la clave: en SQL, dos NULL no se consideran iguales,
--    así que sin él las citas SIN persona asignada (todas las actuales)
--    dejarían de estar protegidas EN SILENCIO. Con coalesce, todas las
--    citas sin persona comparten la "persona 0" y chocan entre sí igual
--    que hoy.
--
--    CRITERIO DE ACEPTACIÓN: una tienda sin personas dadas de alta debe
--    comportarse EXACTAMENTE como antes.
--
--    VUELTA ATRÁS (si algo saliera mal):
--      drop index if exists appointments_store_resource_start_confirmed_unique;
--      create unique index appointments_store_start_at_confirmed_unique
--        on public.appointments (store_id, start_at) where status = 'confirmed';
-- ============================================================

create unique index if not exists appointments_store_resource_start_confirmed_unique
  on public.appointments (store_id, coalesce(resource_id, 0), start_at)
  where status = 'confirmed';

drop index if exists appointments_store_start_at_confirmed_unique;

-- Verificación recomendada tras ejecutar:
--   select indexname from pg_indexes
--   where tablename = 'appointments' and indexname like '%confirmed%';
--   → debe aparecer SOLO appointments_store_resource_start_confirmed_unique
