-- ============================================================
-- B5.2 — APARATOS Y RECURSOS LIMITADOS  (doc 12 bloque 2)
-- Idempotente. Un servicio puede necesitar, además de una persona,
-- un aparato del que hay un número limitado de unidades:
--   Tinte  → 1 persona + 1 sillón de color (de 2 que hay)
--   Mechas → 1 persona + 1 sillón de color
--   Corte  → solo persona
-- Los aparatos se guardan en `resources` con kind='elevador'|'sala'|'otro'
-- y su número de unidades en `resources.units` (creada en migration_equipo).
-- ============================================================

create table if not exists public.service_resources (
  id          bigint generated by default as identity primary key,
  store_id    uuid not null references public.stores (id) on delete cascade,
  service_id  bigint not null references public.services (id)  on delete cascade,
  resource_id bigint not null references public.resources (id) on delete cascade,
  created_at  timestamptz not null default now()
);

-- Un servicio no puede pedir dos veces el mismo aparato
create unique index if not exists service_resources_unico
  on public.service_resources (service_id, resource_id);
create index if not exists service_resources_store_idx
  on public.service_resources (store_id, service_id);

alter table public.service_resources enable row level security;

-- Interruptores de la TIENDA (siempre reversible al comportamiento anterior):
--   usar_equipo=false   → una cita a la vez, como antes de tener equipo
--   usar_aparatos=false → los aparatos no limitan nada
-- Ambos activos por defecto: con los datos vacíos no cambian nada.
alter table public.stores add column if not exists usar_equipo   boolean not null default true;
alter table public.stores add column if not exists usar_aparatos boolean not null default true;

comment on table public.service_resources is
  'Qué aparatos necesita cada servicio (B5.2). Sin filas = el servicio solo necesita una persona.';

-- Verificación:
--   select s.name as servicio, r.name as aparato, r.units
--   from service_resources sr
--   join services s on s.id = sr.service_id
--   join resources r on r.id = sr.resource_id;
