-- =====================================================================
-- SCHEMA CONSOLIDADO — CanalAgenda (SaaS reservas por WhatsApp)
-- =====================================================================
-- FUENTE DE VERDAD para recrear la base de datos desde cero.
-- Generado a partir de la foto REAL del Supabase de producción
-- (information_schema + pg_indexes + pg_constraint, julio 2026),
-- NO desde el schema.sql antiguo (desactualizado, no usar).
--
-- Idempotente: se puede ejecutar sobre una BD vacía o ya existente.
-- Uso: Supabase SQL Editor de un proyecto nuevo → pegar y ejecutar.
--
-- Reglas que este esquema garantiza (NO tocar sin entender el porqué):
--   * Idempotencia de mensajes: unique parcial (store_id, message_id)
--   * Anti doble-reserva: unique parcial (store_id, start_at) WHERE confirmed
--   * Multi-tenant: todas las tablas hijas cuelgan de stores.id (store_id)
-- =====================================================================

-- ---------------------------------------------------------------------
-- 1) STORES — tenant / tienda
-- ---------------------------------------------------------------------
create table if not exists public.stores (
  id                            uuid primary key default gen_random_uuid(),
  name                          text not null,
  timezone                      text not null default 'Europe/Madrid',
  appointment_duration_minutes  integer not null default 30,
  business_email                text,
  business_phone                text,
  created_at                    timestamptz not null default now()
);
-- El estado del onboarding (draft/ready) NO se guarda: se deriva de las conexiones.

-- ---------------------------------------------------------------------
-- 2) WHATSAPP_ACCOUNTS — mapeo phone_number_id → store_id + credenciales
-- ---------------------------------------------------------------------
create table if not exists public.whatsapp_accounts (
  id               uuid primary key default gen_random_uuid(),
  store_id         uuid not null references public.stores (id) on delete cascade,
  phone_number_id  text not null,
  waba_id          text,
  access_token     text not null,
  verify_token     text not null,
  is_active        boolean not null default true,
  token_expires_at timestamptz,  -- null = token permanente (paso 6)
  created_at       timestamptz not null default now()
);

-- Unicidad global de phone_number_id (un número solo puede pertenecer a una fila)
create unique index if not exists whatsapp_accounts_phone_number_id_key
  on public.whatsapp_accounts (phone_number_id);

-- Un solo whatsapp_account por tienda
create unique index if not exists whatsapp_accounts_store_id_key
  on public.whatsapp_accounts (store_id);

-- Variantes parciales por is_active (existen en producción; redundantes con
-- las FULL de arriba pero inocuas — se mantienen por fidelidad al estado real)
create unique index if not exists whatsapp_accounts_phone_number_id_active_unique
  on public.whatsapp_accounts (phone_number_id) where is_active = true;
create unique index if not exists whatsapp_accounts_store_id_active_unique
  on public.whatsapp_accounts (store_id) where is_active = true;

-- ---------------------------------------------------------------------
-- 3) CALENDAR_CONNECTIONS — Google Calendar por tienda
-- ---------------------------------------------------------------------
create table if not exists public.calendar_connections (
  id                  uuid primary key default gen_random_uuid(),
  store_id            uuid not null references public.stores (id) on delete cascade,
  google_calendar_id  text not null,
  mode                text not null default 'shared_service_account',
  created_at          timestamptz not null default now()
);

create unique index if not exists calendar_connections_store_id_key
  on public.calendar_connections (store_id);

-- ---------------------------------------------------------------------
-- 4) CUSTOMERS — cliente final, único por (store_id, phone)
-- ---------------------------------------------------------------------
create table if not exists public.customers (
  id          bigint generated by default as identity primary key,
  store_id    uuid not null references public.stores (id) on delete cascade,
  phone       text not null,
  name        text,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);

-- N8: origen del nombre (perfil_whatsapp | cliente | negocio).
-- Los datos de clientes son SIEMPRE por tienda: un mismo teléfono en dos
-- negocios son dos fichas independientes y NO se comparte nada entre ellas.
alter table public.customers add column if not exists name_source text;

create unique index if not exists customers_store_phone_unique
  on public.customers (store_id, phone);
create index if not exists customers_store_id_idx
  on public.customers (store_id);

-- ---------------------------------------------------------------------
-- 5) MESSAGES — log entrante/saliente + idempotencia por WAMID
-- ---------------------------------------------------------------------
create table if not exists public.messages (
  id           bigint generated by default as identity primary key,
  store_id     uuid not null references public.stores (id) on delete cascade,
  customer_id  bigint references public.customers (id) on delete set null,
  phone        text not null,
  content      text not null,
  from_me      boolean not null default false,
  message_id   text,           -- WAMID de Meta (null en salientes actuales)
  raw_payload  jsonb,          -- payload bruto opcional
  created_at   timestamptz not null default now()
);

-- CRÍTICO — idempotencia: un mismo WAMID no se procesa dos veces por tienda
create unique index if not exists messages_store_message_id_unique
  on public.messages (store_id, message_id)
  where message_id is not null;

create index if not exists messages_store_created_at_idx
  on public.messages (store_id, created_at desc);
create index if not exists idx_messages_phone_created
  on public.messages (phone, created_at desc);
create index if not exists messages_customer_created_at_idx
  on public.messages (customer_id, created_at desc);

-- ---------------------------------------------------------------------
-- 6) APPOINTMENTS — citas
-- ---------------------------------------------------------------------
create table if not exists public.appointments (
  id               bigint generated by default as identity primary key,
  store_id         uuid not null references public.stores (id) on delete cascade,
  customer_id      bigint not null references public.customers (id) on delete cascade,
  phone            text,
  start_at         timestamptz not null,
  end_at           timestamptz not null,
  google_event_id  text,
  status           text not null default 'confirmed'
                     check (status in ('pending', 'confirmed', 'cancelled')),
  source           text not null default 'whatsapp'
                     check (source in ('whatsapp', 'admin')),
  notes            text,
  reminder_24h_sent_at    timestamptz,  -- R1: recordatorio 24 h enviado
  reminder_2h_sent_at     timestamptz,  -- R1: recordatorio 2 h enviado
  confirmed_by_client_at  timestamptz,  -- R1: botón [Confirmo] pulsado
  created_at       timestamptz not null default now(),
  updated_at       timestamptz not null default now()
);
-- NOTA: el check de status en producción se verificó parcialmente (la lista
-- salía truncada en pantalla). Si el real admite más valores, ajustar aquí.

-- CRÍTICO — anti doble-reserva: solo bloquea entre citas CONFIRMADAS.
-- NUNCA convertir en unique full: impediría rereservar huecos cancelados
-- (bug real corregido en migration_fix_appointments_unique_full.sql).
--
-- B5.1 (migration_equipo.sql): ahora es por PERSONA. El coalesce(resource_id, 0)
-- es imprescindible: sin él, las citas sin persona asignada (NULL) dejarían de
-- chocar entre sí y las tiendas de una sola persona perderían la protección.
create unique index if not exists appointments_store_resource_start_confirmed_unique
  on public.appointments (store_id, coalesce(resource_id, 0), start_at)
  where status = 'confirmed';

create unique index if not exists appointments_store_google_event_id_unique
  on public.appointments (store_id, google_event_id);
create index if not exists appointments_store_start_at_idx
  on public.appointments (store_id, start_at);
create index if not exists appointments_store_status_idx
  on public.appointments (store_id, status);
create index if not exists idx_appointments_customer
  on public.appointments (customer_id);
create index if not exists idx_appointments_start
  on public.appointments (start_at);
create index if not exists appointments_store_id_idx
  on public.appointments (store_id);

-- ---------------------------------------------------------------------
-- 7) CONVERSATION_STATE — estado conversacional persistido (stateless)
-- ---------------------------------------------------------------------
create table if not exists public.conversation_state (
  store_id    uuid not null references public.stores (id) on delete cascade,
  phone       text not null,
  state       jsonb not null default '{}',
  expires_at  timestamptz,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now(),
  primary key (store_id, phone)
);

create index if not exists conversation_state_expires_at_idx
  on public.conversation_state (expires_at);

-- ---------------------------------------------------------------------
-- 8) STORE_BUSINESS_HOURS — horarios por tienda (weekday 0=domingo..6=sábado)
-- ---------------------------------------------------------------------
create table if not exists public.store_business_hours (
  id          uuid primary key default gen_random_uuid(),
  store_id    uuid not null references public.stores (id) on delete cascade,
  weekday     smallint not null check (weekday >= 0 and weekday <= 6),
  open_time   time,
  close_time  time,
  is_closed   boolean not null default false,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now(),
  -- Coherencia: cerrado sin horas, o abierto con ambas horas
  check (
    (is_closed = true  and open_time is null     and close_time is null)
    or
    (is_closed = false and open_time is not null and close_time is not null)
  )
);

create unique index if not exists store_business_hours_store_id_weekday_key
  on public.store_business_hours (store_id, weekday);

-- ---------------------------------------------------------------------
-- 9) STORE_USERS — vínculo usuario (Supabase Auth) ↔ tienda  [base paso 4]
-- ---------------------------------------------------------------------
create table if not exists public.store_users (
  id          uuid primary key default gen_random_uuid(),
  store_id    uuid not null references public.stores (id) on delete cascade,
  user_id     uuid not null,   -- auth.users.id (sin FK en producción actual)
  role        text not null default 'owner' check (role in ('owner', 'admin')),
  created_at  timestamptz not null default now()
);

create unique index if not exists store_users_store_id_user_id_key
  on public.store_users (store_id, user_id);

-- ---------------------------------------------------------------------
-- 10) RLS — habilitado sin políticas: el acceso es SIEMPRE vía backend
--     con service_role (que bypassa RLS). Ningún cliente accede directo.
-- ---------------------------------------------------------------------
alter table public.stores               enable row level security;
alter table public.whatsapp_accounts    enable row level security;
alter table public.calendar_connections enable row level security;
alter table public.customers            enable row level security;
alter table public.messages             enable row level security;
alter table public.appointments         enable row level security;
alter table public.conversation_state   enable row level security;
alter table public.store_business_hours enable row level security;
alter table public.store_users          enable row level security;

-- ---------------------------------------------------------------------
-- 11) MÓDULO "LLAMADA PERDIDA → WHATSAPP" (missed-call)
--     Cadena multi-tenant propia: DID (campo To del webhook de voz)
--     → store_phone_numbers → store_id. Ver migration_missed_call_module.sql
--     para el detalle de decisiones de diseño.
-- ---------------------------------------------------------------------
create table if not exists public.store_phone_numbers (
  id          uuid primary key default gen_random_uuid(),
  store_id    uuid not null references public.stores (id) on delete cascade,
  provider    text not null default 'twilio',
  did_e164    text not null,
  is_active   boolean not null default true,
  created_at  timestamptz not null default now()
);
create unique index if not exists store_phone_numbers_did_unique
  on public.store_phone_numbers (did_e164);
create index if not exists store_phone_numbers_store_id_idx
  on public.store_phone_numbers (store_id);

create table if not exists public.missed_call_settings (
  store_id           uuid primary key references public.stores (id) on delete cascade,
  enabled            boolean not null default false,
  monthly_quota      integer not null default 100,
  business_name      text,
  template_name      text not null default 'canalagenda_missed_call_v1',
  template_language  text not null default 'es',
  template_status    text not null default 'pending'
                       check (template_status in ('pending', 'approved', 'rejected')),
  quiet_start        time not null default '21:00',
  quiet_end          time not null default '09:00',
  ticket_medio_eur   numeric(8,2),
  created_at         timestamptz not null default now(),
  updated_at         timestamptz not null default now()
);

create table if not exists public.missed_calls (
  id                        bigint generated by default as identity primary key,
  store_id                  uuid not null references public.stores (id) on delete cascade,
  caller_phone              text,
  is_anonymous              boolean not null default false,
  did_e164                  text not null,
  provider                  text not null default 'twilio',
  provider_call_id          text,
  occurred_at               timestamptz not null default now(),
  status                    text not null default 'pending'
                              check (status in ('pending', 'sent', 'skipped')),
  skip_reason               text
                              check (skip_reason is null or skip_reason in
                                ('quota_exceeded', 'optout', 'anonymous', 'disabled',
                                 'template_not_approved', 'dedupe_24h', 'no_whatsapp_account')),
  template_sent_at          timestamptz,
  wa_message_id             text,
  callback_requested        boolean not null default false,
  resulted_in_conversation  boolean not null default false,
  resulted_in_booking_id    bigint references public.appointments (id) on delete set null,
  created_at                timestamptz not null default now()
);
-- CRÍTICO — idempotencia del webhook de voz (Twilio reintenta CallSid)
create unique index if not exists missed_calls_provider_call_unique
  on public.missed_calls (provider, provider_call_id)
  where provider_call_id is not null;
create index if not exists missed_calls_pending_idx
  on public.missed_calls (store_id, occurred_at)
  where status = 'pending';
create index if not exists missed_calls_store_occurred_idx
  on public.missed_calls (store_id, occurred_at desc);

-- CRÍTICO — dedupe 1 plantilla/(tienda,teléfono)/día natural local (patrón 23505)
create table if not exists public.missed_call_sends (
  store_id    uuid not null references public.stores (id) on delete cascade,
  phone       text not null,
  sent_on     date not null,
  created_at  timestamptz not null default now(),
  primary key (store_id, phone, sent_on)
);

create table if not exists public.contact_optouts (
  store_id    uuid not null references public.stores (id) on delete cascade,
  phone       text not null,
  source      text not null default 'missed_call',
  created_at  timestamptz not null default now(),
  primary key (store_id, phone)
);

alter table public.store_phone_numbers  enable row level security;
alter table public.missed_call_settings enable row level security;
alter table public.missed_calls         enable row level security;
alter table public.missed_call_sends    enable row level security;
alter table public.contact_optouts      enable row level security;

-- ---------------------------------------------------------------------
-- 12) RECORDATORIOS ANTI NO-SHOW (R1) — config por tienda + índice de cola
-- ---------------------------------------------------------------------
create table if not exists public.reminder_settings (
  store_id           uuid primary key references public.stores (id) on delete cascade,
  enabled            boolean not null default false,
  remind_24h         boolean not null default true,
  remind_2h          boolean not null default true,
  template_name      text not null default 'canalagenda_reminder_v1',
  template_language  text not null default 'es',
  template_status    text not null default 'pending'
                       check (template_status in ('pending', 'approved', 'rejected')),
  created_at         timestamptz not null default now(),
  updated_at         timestamptz not null default now()
);

create index if not exists appointments_reminders_due_idx
  on public.appointments (start_at)
  where status = 'confirmed'
    and (reminder_24h_sent_at is null or reminder_2h_sent_at is null);

alter table public.reminder_settings enable row level security;

-- ---------------------------------------------------------------------
-- 13) CATÁLOGO DE SERVICIOS POR VERTICAL (B2, doc 08 §2)
--     El vertical es configuración: vertical_code + services (+ resources
--     preparado para B5). Ver migration_catalogo_servicios.sql.
-- ---------------------------------------------------------------------
alter table public.stores add column if not exists vertical_code text;

create table if not exists public.services (
  id                bigint generated by default as identity primary key,
  store_id          uuid not null references public.stores(id) on delete cascade,
  name              text not null,
  duration_minutes  integer not null check (duration_minutes > 0),
  price_eur         numeric(8,2),
  description       text,
  mode              text not null default 'slot' check (mode in ('slot','franja')),
  is_active         boolean not null default true,
  sort_order        integer not null default 0,
  created_at        timestamptz not null default now()
);
create index if not exists services_store_active_idx
  on public.services (store_id, is_active, sort_order);

create table if not exists public.resources (
  id          bigint generated by default as identity primary key,
  store_id    uuid not null references public.stores(id) on delete cascade,
  name        text not null,
  kind        text not null default 'empleado'
                check (kind in ('empleado','elevador','sala','otro')),
  is_active   boolean not null default true,
  sort_order  integer not null default 0,
  created_at  timestamptz not null default now()
);
create index if not exists resources_store_active_idx
  on public.resources (store_id, is_active, sort_order);

-- B5.1 — turnos y ausencias del equipo (migration_equipo.sql)
alter table public.resources add column if not exists units integer not null default 1;

create table if not exists public.resource_schedules (
  id          bigint generated by default as identity primary key,
  store_id    uuid not null references public.stores (id) on delete cascade,
  resource_id bigint not null references public.resources (id) on delete cascade,
  weekday     smallint not null check (weekday >= 0 and weekday <= 6),
  open_time   time not null,
  close_time  time not null,
  created_at  timestamptz not null default now(),
  constraint resource_schedules_horas check (close_time > open_time)
);
create index if not exists resource_schedules_recurso_idx on public.resource_schedules (resource_id, weekday);

create table if not exists public.resource_absences (
  id          bigint generated by default as identity primary key,
  store_id    uuid not null references public.stores (id) on delete cascade,
  resource_id bigint not null references public.resources (id) on delete cascade,
  start_date  date not null,
  end_date    date not null,
  reason      text,
  created_at  timestamptz not null default now(),
  constraint resource_absences_rango check (end_date >= start_date)
);
create index if not exists resource_absences_recurso_idx on public.resource_absences (resource_id, start_date, end_date);

alter table public.resource_schedules enable row level security;
alter table public.resource_absences  enable row level security;

-- B5.2 — qué aparatos necesita cada servicio (migration_recursos.sql)
create table if not exists public.service_resources (
  id          bigint generated by default as identity primary key,
  store_id    uuid not null references public.stores (id) on delete cascade,
  service_id  bigint not null references public.services (id)  on delete cascade,
  resource_id bigint not null references public.resources (id) on delete cascade,
  created_at  timestamptz not null default now()
);
create unique index if not exists service_resources_unico
  on public.service_resources (service_id, resource_id);
alter table public.service_resources enable row level security;

-- Interruptores de la tienda: apagarlos devuelve el comportamiento anterior
alter table public.stores add column if not exists usar_equipo   boolean not null default true;
alter table public.stores add column if not exists usar_aparatos boolean not null default true;
-- Vigilancia de borrados hechos directamente en Google Calendar
alter table public.stores add column if not exists usar_sync_calendar boolean not null default true;
-- Rejilla: cada cuántos minutos puede empezar una cita (0 = bloques del servicio)
alter table public.stores add column if not exists paso_huecos_min smallint not null default 30;

alter table public.appointments add column if not exists service_id  bigint references public.services(id)  on delete set null;
alter table public.appointments add column if not exists resource_id bigint references public.resources(id) on delete set null;
alter table public.appointments add column if not exists extra       jsonb;

alter table public.services  enable row level security;
alter table public.resources enable row level security;

-- =====================================================================
-- 14. FLAGS PREMIUM POR TIENDA (doc 09 — P1 smart_slots y siguientes)
--     Añadido por migration_premium_features.sql. OFF por defecto:
--     con '{}' el comportamiento es idéntico al histórico.
-- =====================================================================

alter table public.stores
  add column if not exists premium_features jsonb not null default '{}'::jsonb;

alter table public.stores
  add column if not exists features_disabled jsonb not null default '{}'::jsonb;

-- =====================================================================
-- 15. LISTA DE ESPERA (P3, doc 09) — añadido por migration_waitlist.sql
-- =====================================================================

create table if not exists public.waitlist (
  id            bigint generated by default as identity primary key,
  store_id      uuid not null references public.stores (id) on delete cascade,
  customer_id   bigint not null references public.customers (id) on delete cascade,
  service_id    bigint references public.services (id) on delete set null,
  desired_date  date,
  status        text not null default 'waiting'
                  check (status in ('waiting','notified','converted','cancelled','expired')),
  created_at    timestamptz not null default now(),
  notified_at   timestamptz
);
create index if not exists waitlist_store_status_idx
  on public.waitlist (store_id, status, desired_date);

-- =====================================================================
-- 16. CIERRES Y VACACIONES (doc 12 bloque 1) — migration_horarios_cierres
--     Se suman al horario semanal: getDayHours() combina ambos.
-- =====================================================================

create table if not exists public.store_closures (
  id          bigint generated by default as identity primary key,
  store_id    uuid not null references public.stores (id) on delete cascade,
  start_date  date not null,
  end_date    date not null,
  reason      text,
  created_at  timestamptz not null default now(),
  constraint store_closures_rango_valido check (end_date >= start_date)
);
create index if not exists store_closures_store_range_idx
  on public.store_closures (store_id, start_date, end_date);
alter table public.store_closures enable row level security;
create unique index if not exists waitlist_unique_waiting
  on public.waitlist (store_id, customer_id, coalesce(desired_date, '1900-01-01'::date))
  where status = 'waiting';
alter table public.waitlist enable row level security;

-- =====================================================================
-- VERIFICACIÓN RÁPIDA tras ejecutar (debe devolver 15 tablas):
--   select table_name from information_schema.tables
--   where table_schema='public' order by 1;
-- =====================================================================
